
import type { PlantillaToolsMapping, SIDCGenerationOptions } from '../types';
import type { PathOptions } from 'leaflet';
import { PlantillaType, PICCElementType } from '../types';

import {
  PICC_PATH_OPTIONS_FRIENDLY, PICC_PATH_OPTIONS_HOSTILE, PICC_PATH_OPTIONS_NEUTRAL, PICC_PATH_OPTIONS_CONTROL,
  SIDC_AFFILIATION_FRIEND, SIDC_AFFILIATION_HOSTILE, SIDC_AFFILIATION_NEUTRAL, SIDC_AFFILIATION_UNKNOWN,
  SIDC_DIMENSION_GROUND, SIDC_STATUS_PRESENT, DEFAULT_PICC_SYMBOL_SIZE
} from '../constants';

import { ShareIcon } from '../components/icons/ShareIcon';
import { Squares2X2Icon } from '../components/icons/Squares2X2Icon';
import { StopCircleIcon } from '../components/icons/StopCircleIcon';
import { FlagIcon } from '../components/icons/FlagIcon';
import { MapPinIcon } from '../components/icons/MapPinIcon';
import { ExclamationTriangleIcon } from '../components/icons/ExclamationTriangleIcon';
import { ShieldCheckIcon } from '../components/icons/ShieldCheckIcon';
import { ShieldExclamationIcon } from '../components/icons/ShieldExclamationIcon';

const defaultFriendlyLine: PathOptions = { ...PICC_PATH_OPTIONS_FRIENDLY, fillOpacity: 0 };
const defaultFriendlyArea: PathOptions = PICC_PATH_OPTIONS_FRIENDLY;
const defaultHostileLine: PathOptions = { ...PICC_PATH_OPTIONS_HOSTILE, fillOpacity: 0 };
const defaultHostileArea: PathOptions = PICC_PATH_OPTIONS_HOSTILE;
const defaultNeutralLine: PathOptions = { ...PICC_PATH_OPTIONS_NEUTRAL, fillOpacity: 0 };
const defaultNeutralArea: PathOptions = PICC_PATH_OPTIONS_NEUTRAL;
const defaultControlLine: PathOptions = PICC_PATH_OPTIONS_CONTROL;

// SIDC Options for generic point symbols (units, etc.)
// These will typically use 10-char tactical graphic SIDCs like SFGPUC----
const pointSymbolSidcOptions = (affiliation: 'F' | 'H' | 'N' | 'U'): SIDCGenerationOptions => ({
  affiliation,
  battleDimension: SIDC_DIMENSION_GROUND,
  status: SIDC_STATUS_PRESENT,
});

export const PlantillaPICCConfig: PlantillaToolsMapping = {
  [PlantillaType.SITUACION_ACTUAL]: {
    label: "Situación Actual",
    elements: [
      { type: PICCElementType.FRIENDLY_UNIT_POINT_SIT, label: "Und. Amiga", icon: ShieldCheckIcon, colorClass: 'bg-blue-500 hover:bg-blue-600', defaultOptions: { sidcOptions: pointSymbolSidcOptions(SIDC_AFFILIATION_FRIEND), labelPrompt: "Nombre Unidad Amiga (Ej: A/1-506)", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } },
      { type: PICCElementType.ENEMY_UNIT_POINT_SIT, label: "Und. Enemiga", icon: ShieldExclamationIcon, colorClass: 'bg-red-500 hover:bg-red-600', defaultOptions: { sidcOptions: pointSymbolSidcOptions(SIDC_AFFILIATION_HOSTILE), labelPrompt: "Nombre Unidad Enemiga (Ej: Pelotón GAO)", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } },
      { type: PICCElementType.NEUTRAL_POINT_SIT, label: "Punto Neutral", icon: MapPinIcon, colorClass: 'bg-green-500 hover:bg-green-600', defaultOptions: { sidcOptions: pointSymbolSidcOptions(SIDC_AFFILIATION_NEUTRAL), labelPrompt: "Nombre Punto Neutral", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } },
      { type: PICCElementType.CIVILIAN_POINT_SIT, label: "Punto Civil", icon: MapPinIcon, colorClass: 'bg-yellow-500 hover:bg-yellow-600 text-black', defaultOptions: { sidcOptions: { affiliation: SIDC_AFFILIATION_NEUTRAL }, labelPrompt: "Descripción Punto Civil", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } }, // SIDC SNGPCV---- generated by getPICCElementSIDC
      { type: PICCElementType.LINE_OF_CONTACT, label: "Línea Contacto", icon: FlagIcon, colorClass: 'bg-red-600 hover:bg-red-700', defaultOptions: { pathOptions: defaultHostileLine, labelPrompt: "LOC" } },
      { type: PICCElementType.CONTROL_PHASE_LINE, label: "Línea de Fase (Actual)", icon: FlagIcon, colorClass: 'bg-gray-600 hover:bg-gray-700', defaultOptions: { pathOptions: defaultControlLine, labelPrompt: "Nombre Línea de Fase" } },
    ],
  },
  [PlantillaType.MANIOBRA_PROPUESTA]: {
    label: "Maniobra Propuesta",
    elements: [
      { type: PICCElementType.FRIENDLY_MAIN_ATTACK_AXIS, label: "Eje Ataque Ppal.", icon: ShareIcon, colorClass: 'bg-blue-600 hover:bg-blue-700', defaultOptions: { pathOptions: defaultFriendlyLine, labelPrompt: "Eje Ppal." } },
      { type: PICCElementType.FRIENDLY_SUPPORTING_ATTACK_AXIS, label: "Eje Ataque Sec.", icon: ShareIcon, colorClass: 'bg-blue-500 hover:bg-blue-600', defaultOptions: { pathOptions: { ...defaultFriendlyLine, dashArray: '5,5' }, labelPrompt: "Eje Sec." } },
      { type: PICCElementType.FRIENDLY_ASSEMBLY_AREA, label: "Área Reunión", icon: Squares2X2Icon, colorClass: 'bg-blue-500 hover:bg-blue-600', defaultOptions: { pathOptions: defaultFriendlyArea, sidcOptions: { affiliation: SIDC_AFFILIATION_FRIEND }, labelPrompt: "AR (Amiga)" } },
      { type: PICCElementType.FRIENDLY_OBJECTIVE, label: "Objetivo", icon: StopCircleIcon, colorClass: 'bg-blue-700 hover:bg-blue-800', defaultOptions: { pathOptions: defaultFriendlyArea, sidcOptions: { affiliation: SIDC_AFFILIATION_FRIEND }, labelPrompt: "Nombre Objetivo" } },
      { type: PICCElementType.FRIENDLY_TASK_MANEUVER, label: "Tarea Maniobra", icon: FlagIcon, colorClass: 'bg-sky-500 hover:bg-sky-600', defaultOptions: { pathOptions: defaultFriendlyLine, labelPrompt: "Tarea (Ej: FIJAR, ATACAR)" } },
      { type: PICCElementType.CONTROL_PHASE_LINE, label: "Línea de Fase (Plan.)", icon: FlagIcon, colorClass: 'bg-black text-white hover:bg-gray-700', defaultOptions: { pathOptions: defaultControlLine, labelPrompt: "Nombre Línea de Fase" } },
      { type: PICCElementType.CONTROL_CHECKPOINT, label: "Punto Control", icon: MapPinIcon, colorClass: 'bg-black text-white hover:bg-gray-700', defaultOptions: { sidcOptions: { affiliation: SIDC_AFFILIATION_NEUTRAL }, labelPrompt: "Nombre Punto Control", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } },
    ],
  },
  [PlantillaType.OBSTACULOS]: {
    label: "Obstáculos",
    elements: [
      { type: PICCElementType.OBSTACLE_MINEFIELD_PLANNED, label: "CM Planif. (Amigo)", icon: ExclamationTriangleIcon, colorClass: 'bg-blue-500 hover:bg-blue-600', defaultOptions: { pathOptions: defaultFriendlyArea, sidcOptions: { affiliation: SIDC_AFFILIATION_FRIEND }, labelPrompt: "CM Planificado" } },
      { type: PICCElementType.OBSTACLE_MINEFIELD_DETECTED, label: "CM Detect. (Enem.)", icon: ExclamationTriangleIcon, colorClass: 'bg-red-500 hover:bg-red-600', defaultOptions: { pathOptions: defaultHostileArea, sidcOptions: { affiliation: SIDC_AFFILIATION_HOSTILE }, labelPrompt: "CM Detectado" } },
      { type: PICCElementType.OBSTACLE_BARRIER_GENERIC, label: "Barrera Genérica", icon: ExclamationTriangleIcon, colorClass: 'bg-yellow-600 hover:bg-yellow-700 text-black', defaultOptions: { pathOptions: defaultNeutralArea, labelPrompt: "Tipo Barrera", sidcOptions: { affiliation: SIDC_AFFILIATION_UNKNOWN } } }, // SIDC GUMO------ etc.
      { type: PICCElementType.OBSTACLE_DEMOLITION_PLANNED, label: "Demolición Planif.", icon: ExclamationTriangleIcon, colorClass: 'bg-orange-500 hover:bg-orange-600', defaultOptions: { sidcOptions: { affiliation: SIDC_AFFILIATION_FRIEND }, labelPrompt: "Obj. Demolición", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } },
    ],
  },
  [PlantillaType.APOYO_FUEGOS]: {
    label: "Apoyo de Fuegos",
    elements: [
      { type: PICCElementType.TARGET_REFERENCE_POINT, label: "Blanco / PRT", icon: StopCircleIcon, colorClass: 'bg-red-700 hover:bg-red-800', defaultOptions: { sidcOptions: { affiliation: SIDC_AFFILIATION_HOSTILE }, labelPrompt: "ID Blanco", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } },
      { type: PICCElementType.FSCL_LINE, label: "LCAF / FSCL", icon: FlagIcon, colorClass: 'bg-purple-500 hover:bg-purple-600', defaultOptions: { pathOptions: { color: '#800080', weight: 2, dashArray: '10, 5, 2, 5' }, labelPrompt: "FSCL" } },
      { type: PICCElementType.CFL_LINE, label: "LCF / CFL", icon: FlagIcon, colorClass: 'bg-indigo-500 hover:bg-indigo-600', defaultOptions: { pathOptions: { color: '#4B0082', weight: 2, dashArray: '10, 5' }, labelPrompt: "CFL" } },
      { type: PICCElementType.NFA_AREA, label: "Área Fuego Prohibido", icon: Squares2X2Icon, colorClass: 'bg-pink-700 hover:bg-pink-800', defaultOptions: { pathOptions: { color: '#FF00FF', weight: 2, fillColor: '#FF00FF', fillOpacity: 0.3, dashArray: '5,5' }, labelPrompt: "AFP / NFA" } },
      { type: PICCElementType.RFA_AREA, label: "Área Fuego Restringido", icon: Squares2X2Icon, colorClass: 'bg-rose-700 hover:bg-rose-800', defaultOptions: { pathOptions: { color: '#FFC0CB', weight: 2, fillColor: '#FFC0CB', fillOpacity: 0.3, dashArray: '5,5' }, labelPrompt: "AFR / RFA" } },
    ],
  },
  [PlantillaType.INTELIGENCIA_ENEMIGA]: {
    label: "Inteligencia Enemiga",
    elements: [
      { type: PICCElementType.ENEMY_UNIT_POINT_SIT, label: "Und. Enemiga (Intel)", icon: ShieldExclamationIcon, colorClass: 'bg-red-500 hover:bg-red-600', defaultOptions: { sidcOptions: pointSymbolSidcOptions(SIDC_AFFILIATION_HOSTILE), labelPrompt: "Und. Enemiga (Info)", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } },
      { type: PICCElementType.NAI_POINT, label: "ADI / NAI", icon: MapPinIcon, colorClass: 'bg-yellow-500 hover:bg-yellow-600 text-black', defaultOptions: { sidcOptions: { affiliation: SIDC_AFFILIATION_NEUTRAL }, labelPrompt: "NAI", defaultSymbolSize: DEFAULT_PICC_SYMBOL_SIZE } }, // SIDC GNTPOI----
      { type: PICCElementType.TPL_LINE, label: "LTP / TPL", icon: FlagIcon, colorClass: 'bg-red-600 hover:bg-red-700', defaultOptions: { pathOptions: defaultHostileLine, labelPrompt: "LTP" } },
      { type: PICCElementType.ENEMY_DEFENSIVE_LINE, label: "Línea Def. Enemiga", icon: FlagIcon, colorClass: 'bg-red-700 hover:bg-red-800', defaultOptions: { pathOptions: { ...defaultHostileLine, dashArray: '10, 5' }, labelPrompt: "Línea Defensiva" } },
      { type: PICCElementType.ENEMY_COA_AXIS, label: "Eje C/A Enemigo", icon: ShareIcon, colorClass: 'bg-red-600 hover:bg-red-700', defaultOptions: { pathOptions: defaultHostileLine, labelPrompt: "Probable C/A Enemigo" } },
    ],
  },
};